### Logestic Regression 

In [1]:
import pandas as pd
import numpy as np

In [2]:
file_path = "Titanic_02.csv"
data = pd.read_csv(file_path)
dataset = pd.DataFrame(data)
dataset.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex  Age  SibSp  \
0                            Braund, Mr. Owen Harris    male   22      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female   38      1   
2                             Heikkinen, Miss. Laina  female   26      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female   35      1   
4                           Allen, Mr. William Henry    male   35      0   

   Parch            Ticket     Fare    Cabin Embarked  
0      0         A/5 21171   7.2500  B96 B98        S  
1      0          PC 17599  71.2833      C85        C  
2      0  STON/O2. 3101282   7.9250  B96 B98        S  
3      0            113803  53.1000     C123        S  
4      0            373450   8.0500  B96 B98        S

In [3]:
dataset.shape

(891, 12)

In [4]:
dataset.isna().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

In [5]:
dataset.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age              int64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [6]:
dataset.Age = dataset.Age.astype('int64')
dataset.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age              int64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [7]:
dataset.corr()

PassengerId  Survived    Pclass       Age     SibSp     Parch  \
PassengerId     1.000000 -0.005007 -0.035144  0.033741 -0.057527 -0.001652   
Survived       -0.005007  1.000000 -0.338481 -0.067809 -0.035322  0.081629   
Pclass         -0.035144 -0.338481  1.000000 -0.335071  0.083081  0.018443   
Age             0.033741 -0.067809 -0.335071  1.000000 -0.232743 -0.176744   
SibSp          -0.057527 -0.035322  0.083081 -0.232743  1.000000  0.414838   
Parch          -0.001652  0.081629  0.018443 -0.176744  0.414838  1.000000   
Fare            0.012658  0.257307 -0.549500  0.093856  0.159651  0.216225   

                 Fare  
PassengerId  0.012658  
Survived     0.257307  
Pclass      -0.549500  
Age          0.093856  
SibSp        0.159651  
Parch        0.216225  
Fare         1.000000

## Define the the Target variable and features

In [8]:
y = dataset.loc[:, dataset.columns == 'Survived']
x = dataset.loc[:, dataset.columns != 'Survived']

## Define feature and drop
#### 1- columns "Name", "Passenger Id" and "Ticket" have been deleted from the features beacuse they do not seem to be very useful in the prediction model

In [9]:
X = x.drop(['Name', 'PassengerId', 'Ticket'], axis = 1)
X.head()

Pclass     Sex  Age  SibSp  Parch     Fare    Cabin Embarked
0       3    male   22      1      0   7.2500  B96 B98        S
1       1  female   38      1      0  71.2833      C85        C
2       3  female   26      0      0   7.9250  B96 B98        S
3       1  female   35      1      0  53.1000     C123        S
4       3    male   35      0      0   8.0500  B96 B98        S

### Transform categorical variables with Dummy values

In [10]:
x_data = pd.get_dummies(X, columns = ['Sex', 'Cabin','Embarked'])

In [11]:
x_data.head(2)

Pclass  Age  SibSp  Parch     Fare  Sex_female  Sex_male  Cabin_A10  \
0       3   22      1      0   7.2500           0         1          0   
1       1   38      1      0  71.2833           1         0          0   

   Cabin_A14  Cabin_A16  ...  Cabin_F G73  Cabin_F2  Cabin_F33  Cabin_F38  \
0          0          0  ...            0         0          0          0   
1          0          0  ...            0         0          0          0   

   Cabin_F4  Cabin_G6  Cabin_T  Embarked_C  Embarked_Q  Embarked_S  
0         0         0        0           0           0           1  
1         0         0        0           1           0           0  

[2 rows x 157 columns]

### Split dataset into train and test and apply Logistic Regression model

In [12]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x_data, y, test_size = 0.3, random_state = 0)

In [13]:
from sklearn.linear_model import LogisticRegression
logistic_reg = LogisticRegression()
logistic_reg.fit(x_train, y_train)

C:\Users\hoori\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
C:\Users\hoori\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [14]:
y_pred = logistic_reg.predict(x_test)

### Calculate accuracy score of the logistic regression model

In [15]:
from sklearn.metrics import classification_report, accuracy_score

In [16]:
print(classification_report(y_test, y_pred))
score = accuracy_score(y_test, y_pred)
print("Accuracy of logistic regression classifier on test set: " + str(score))

              precision    recall  f1-score   support

           0       0.85      0.85      0.85       168
           1       0.75      0.75      0.75       100

    accuracy                           0.81       268
   macro avg       0.80      0.80      0.80       268
weighted avg       0.81      0.81      0.81       268

Accuracy of logistic regression classifier on test set: 0.8134328358208955


### The accuracy score tells that the model correctly identified the target function 81% of the time

### Feature Selection

### Variance Threshold

This feature selection algorithm looks only at the features (X), not the desired outputs (y)

Parameters:

thresholdfloat, default=0
Features with a training-set variance lower than this threshold will be removed.

The default is to keep all features with non-zero variance, i.e. remove the features that have the same value in all samples.

In [21]:
variance = x_train.var()
print(variance)

Pclass           0.706704
Age            169.960455
SibSp            1.352315
Parch            0.692366
Fare          2328.801583
                 ...     
Cabin_G6         0.003205
Cabin_T          0.001605
Embarked_C       0.143533
Embarked_Q       0.081939
Embarked_S       0.194258
Length: 157, dtype: float64


In [34]:
from sklearn.feature_selection import VarianceThreshold

In [35]:
x_train.shape

(623, 157)

In [56]:
# Create an object from the varianve threshold method and fit it of the X (features)

selector = VarianceThreshold(threshold=0.1)
new_features = selector.fit_transform(x_train)

In [57]:
new_features.shape

(623, 10)

In [58]:
# Return the boolean variable which indicates if the feature remains or not

selector.get_support()

array([ True,  True,  True,  True,  True,  True,  True, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
        True, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,

Compress(): This iterator selectively picks the values to print from the passed container according to the boolean list value passed as other arguments.

In [61]:
?compress

In [62]:
from itertools import compress
features = list(x_train.columns)
feature_select = list(compress(features, selector.get_support()))

In [63]:
feature_select

['Pclass',
 'Age',
 'SibSp',
 'Parch',
 'Fare',
 'Sex_female',
 'Sex_male',
 'Cabin_B96 B98',
 'Embarked_C',
 'Embarked_S']

### RFE

Import Recursive Feature Elimination from Sklearn library in Python

In [64]:
from sklearn.feature_selection import RFE

RFE has some parameters that should be tuned

estimator = the model that you fitted and you want to check its accuracy after removing each feature

n_features_to_select = The number of features to select at the end of process. If None, half of the features are selected

In [65]:
logreg_rfe = RFE(estimator=logistic_reg, n_features_to_select = None)
logreg_rfe.fit(x_train, y_train)

C:\Users\hoori\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
C:\Users\hoori\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\hoori\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel

RFE(estimator=LogisticRegression())

Outputs:
    
.support_ : True means that feature is selected

.ranking_ : Returns the important features (n_features_to_select) by 1 and the rest of the features in order ranking.

In [66]:
logreg_rfe.support_

array([ True, False,  True, False, False,  True,  True,  True,  True,
       False,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False, False,  True,  True,
       False, False, False, False, False, False,  True, False, False,
       False, False, False, False, False, False, False,  True, False,
       False, False, False, False, False, False,  True,  True, False,
        True, False, False,  True, False,  True,  True,  True, False,
        True, False, False,  True,  True, False,  True, False,  True,
       False, False,  True, False,  True, False,  True, False, False,
       False, False, False,  True,  True,  True, False, False,  True,
       False, False,  True,  True,  True,  True, False, False, False,
       False, False, False,  True, False, False,  True, False,  True,
        True,  True, False, False, False,  True, False,  True, False,
        True,  True,  True, False, False,  True,  True,  True,  True,
        True,  True,

In [67]:
logreg_rfe.ranking_

array([ 1, 41,  1, 40, 53,  1,  1,  1,  1, 26,  1,  1,  1,  1, 65,  1,  1,
        1,  1,  1,  1,  1,  1, 71, 52,  1,  1, 49,  8, 20, 56, 16, 72,  1,
       47, 32, 68, 79, 43,  6, 55, 50, 66,  1, 59, 69, 23,  7, 60, 45, 38,
        1,  1, 75,  1,  9, 22,  1, 80,  1,  1,  1,  2,  1, 19, 12,  1,  1,
        4,  1, 39,  1, 36, 35,  1, 54,  1, 34,  1, 78, 64, 46, 28, 73,  1,
        1,  1, 74, 63,  1, 57, 48,  1,  1,  1,  1, 18, 25, 58, 13, 37, 24,
        1, 29, 15,  1, 42,  1,  1,  1, 31, 30, 61,  1, 21,  1, 76,  1,  1,
        1, 14, 70,  1,  1,  1,  1,  1,  1,  1,  1, 17, 62, 44,  1, 33,  3,
        1, 27,  1,  1,  1, 11, 77,  1,  1,  1, 10, 67,  1,  1,  5,  1,  1,
        1,  1,  1, 51])

In [68]:
y_pred_2 = logreg_rfe.predict(x_test)

In [69]:
print(classification_report(y_test, y_pred_2))
score_2 = accuracy_score(y_test, y_pred_2)
print("Accuracy of logistic regression classifier on test set: " + str(score_2))

              precision    recall  f1-score   support

           0       0.85      0.85      0.85       168
           1       0.74      0.75      0.75       100

    accuracy                           0.81       268
   macro avg       0.80      0.80      0.80       268
weighted avg       0.81      0.81      0.81       268

Accuracy of logistic regression classifier on test set: 0.8097014925373134


### !!! The model was not improved by RFE !!!